" set backgroud
 colorscheme dracula

" enable syntax hightlight
syntax on

" show the relative line number in the left hand size parrarel with actual line number
set relativenumber
set number
set numberwidth=4

set ruler " show cursor position all the time
set showmatch " show matching brackets

" change line number of relativenumber
hi LineNrAbove guifg=grey ctermfg=grey
hi LineNr ctermfg=yellow
hi LineNrBelow guifg=grey ctermfg=grey

" auto-complete brackets
inoremap ( ()<Left>
inoremap [ []<Left>
inoremap { {}<Left>
inoremap " ""<Left>

" map key
" <CR> is like Enter in keyboard
" map <C-p> :!python3 %<CR>
" map <Leader>run :!python3 %<CR>

" keymap to refresh NERDTree
" nmap <Leader>r :NERDTreeFocus<cr>R<c-w><c-p>
